-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alcohol_2018
(
    id integer NOT NULL DEFAULT nextval('alcohol_2018_id_seq'::regclass),
    "Country_ID" character varying COLLATE pg_catalog."default",
    "Year" integer,
    "Indicator" character varying COLLATE pg_catalog."default",
    "Sex" character varying COLLATE pg_catalog."default",
    "First Tooltip" double precision,
    CONSTRAINT alcohol_2018_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.happiness_2018
(
    "Rank" integer,
    "Country_ID" character varying COLLATE pg_catalog."default" NOT NULL,
    "Happiness Score" double precision,
    "GDP per capita" double precision,
    "Healthy life expectancy" double precision,
    CONSTRAINT happiness_2018_pkey PRIMARY KEY ("Country_ID")
);

CREATE TABLE IF NOT EXISTS public.tobacco_2018
(
    id integer NOT NULL DEFAULT nextval('tobacco_2018_id_seq'::regclass),
    "Country_Id" character varying COLLATE pg_catalog."default",
    "Year" integer,
    "Indicator" character varying COLLATE pg_catalog."default",
    "Sex" character varying COLLATE pg_catalog."default",
    "First Tooltip" double precision,
    CONSTRAINT tobacco_2018_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.alcohol_2018
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public.happiness_2018 ("Country_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tobacco_2018
    ADD FOREIGN KEY ("Country_Id")
    REFERENCES public.happiness_2018 ("Country_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;